meta_product_name: "Fridgy"
meta_title: "Fridgy - Get Instant Recipes For Your Ingredients At Home"
meta_description: "Fridgy is an app that specialized in controlling the ingredients you have at home and providing you with instant recipes."
  # meta_image: "cover.png" # should exist in `app/assets/images/`
